---
title: "Optimal Parameters Geographical Detector(OPGD)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{OPGD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



### Load data and package


``` r
library(terra)
library(tidyverse)
library(gdverse)
fvcpath = "https://github.com/SpatLyu/rdevdata/raw/main/FVC.tif"
fvc = terra::rast(paste0("/vsicurl/",fvcpath))
fvc = aggregate(fvc,fact = 5)
fvc
## class       : SpatRaster 
## dimensions  : 84, 114, 13  (nrow, ncol, nlyr)
## resolution  : 5000, 5000  (x, y)
## extent      : -92742.16, 477257.8, 3589385, 4009385  (xmin, xmax, ymin, ymax)
## coord. ref. : Asia_North_Albers_Equal_Area_Conic 
## source(s)   : memory
## names       :       fvc,   premax,    premin,   presum,   tmpmax,    tmpmin, ... 
## min values  : 0.1527159, 111.2089,  2.340401, 3834.887, 10.92638, -9.976424, ... 
## max values  : 0.8905939, 247.1408, 75.933422, 8276.911, 26.72104,  1.101411, ...
```


``` r
names(fvc)
##  [1] "fvc"    "premax" "premin" "presum" "tmpmax" "tmpmin" "tmpavg" "pop"    "ntl"   
## [10] "lulc"   "elev"   "slope"  "aspect"
```

### Convert data from `SpatRaster` to `tibble`


``` r
fvc = as_tibble(terra::as.data.frame(fvc,na.rm = T))
head(fvc)
## # A tibble: 6 × 13
##     fvc premax premin presum tmpmax tmpmin tmpavg   pop   ntl  lulc  elev slope aspect
##   <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
## 1 0.188   163.   6.86  3992.   21.2  -7.09   8.54  5.64  9.10    10 1645.  2.96   122.
## 2 0.162   162.   5.23  3922.   21.7  -6.90   8.92 23.1  10.5     10 1539.  1.86   174.
## 3 0.168   168.   4.15  4040.   21.2  -7.22   8.53  9.73  5.58    10 1611.  3.19   192.
## 4 0.186   174.   5.99  4254.   20.8  -7.42   8.21  6.84  2.89    10 1677.  3.32   213.
## 5 0.189   164.   7.86  4047.   21.2  -7.00   8.58  2.36 12.3     10 1643.  2.79   132.
## 6 0.171   161.   5.23  3944.   21.7  -6.85   8.91  3.17 10.1     10 1553.  1.93   137.
```

### Determine optimal discretization parameters

Only `lulc` is a discrete category variable in the `fvc` data, we need to discretize others.
We can use `gd_bestunidisc()` to discretize them based on geodetector q-statistic.


``` r
set.seed(12345678)
tictoc::tic()
g = gd_bestunidisc(fvc ~ .,data = select(fvc,-lulc),discnum = 2:15,cores = 6)
tictoc::toc()
## 3.99 sec elapsed
```


``` r
g
## $x
##  [1] "aspect" "elev"   "ntl"    "pop"    "premax" "premin" "presum" "slope"  "tmpavg"
## [10] "tmpmax" "tmpmin"
## 
## $k
##  [1] 12 14 14 14 15 13 15 14 15 15 15
## 
## $method
##  [1] "pretty"   "quantile" "fisher"   "quantile" "fisher"   "fisher"   "fisher"  
##  [8] "fisher"   "fisher"   "quantile" "fisher"  
## 
## $disv
## # A tibble: 5,240 × 11
##    aspect  elev   ntl   pop premax premin presum slope tmpavg tmpmax tmpmin
##     <int> <int> <int> <int>  <int>  <int>  <int> <int>  <int>  <int>  <int>
##  1      7    11     5     2      7      1      1     5      7     10      3
##  2      9    10     5     5      6      1      1     3      8     11      3
##  3     10    11     4     2      7      1      1     5      7     10      3
##  4     11    11     3     2      8      1      2     5      6      8      3
##  5      7    11     5     1      7      1      1     4      7     10      3
##  6      7    10     5     1      6      1      1     3      8     11      3
##  7      7     9     5     3      6      1      1     2      8     12      3
##  8     11     9     5     2      6      1      1     3      8     12      3
##  9      9    11     6     7      7      1      1     5      7     10      3
## 10     11    10     5     3      7      1      1     4      8     11      3
## # ℹ 5,230 more rows
```

``` r
new.fvc = g$disv
new.fvc
## # A tibble: 5,240 × 11
##    aspect  elev   ntl   pop premax premin presum slope tmpavg tmpmax tmpmin
##     <int> <int> <int> <int>  <int>  <int>  <int> <int>  <int>  <int>  <int>
##  1      7    11     5     2      7      1      1     5      7     10      3
##  2      9    10     5     5      6      1      1     3      8     11      3
##  3     10    11     4     2      7      1      1     5      7     10      3
##  4     11    11     3     2      8      1      2     5      6      8      3
##  5      7    11     5     1      7      1      1     4      7     10      3
##  6      7    10     5     1      6      1      1     3      8     11      3
##  7      7     9     5     3      6      1      1     2      8     12      3
##  8     11     9     5     2      6      1      1     3      8     12      3
##  9      9    11     6     7      7      1      1     5      7     10      3
## 10     11    10     5     3      7      1      1     4      8     11      3
## # ℹ 5,230 more rows
```

The `new.fvc`  is the discrete result of the optimal discretization parameter based on the Q statistic of the geographic detector,we can combine it with `fvc` and `lulc` col in `fvc` tibble now.


``` r
new.fvc = bind_cols(select(fvc,fvc,lulc),new.fvc)
new.fvc
## # A tibble: 5,240 × 13
##      fvc  lulc aspect  elev   ntl   pop premax premin presum slope tmpavg tmpmax tmpmin
##    <dbl> <dbl>  <int> <int> <int> <int>  <int>  <int>  <int> <int>  <int>  <int>  <int>
##  1 0.188    10      7    11     5     2      7      1      1     5      7     10      3
##  2 0.162    10      9    10     5     5      6      1      1     3      8     11      3
##  3 0.168    10     10    11     4     2      7      1      1     5      7     10      3
##  4 0.186    10     11    11     3     2      8      1      2     5      6      8      3
##  5 0.189    10      7    11     5     1      7      1      1     4      7     10      3
##  6 0.171    10      7    10     5     1      6      1      1     3      8     11      3
##  7 0.153    10      7     9     5     3      6      1      1     2      8     12      3
##  8 0.163    10     11     9     5     2      6      1      1     3      8     12      3
##  9 0.176    10      9    11     6     7      7      1      1     5      7     10      3
## 10 0.177    10     11    10     5     3      7      1      1     4      8     11      3
## # ℹ 5,230 more rows
```

### Run geodetector

Then ,we can run geodetector model by `gd()` function.


``` r
gd(fvc ~ .,data = new.fvc,type = 'factor')
## Spatial Stratified Heterogeneity Test 
##  
##           Factor detector
```


------------------------------------
 variable   Q-statistic    P-value  
---------- ------------- -----------
  presum       0.662      4.039e-10 

   lulc       0.6597      8.782e-10 

  premin      0.4596      3.471e-10 

  tmpmin      0.4351      3.726e-10 

  tmpmax      0.2594      3.131e-10 

   elev       0.2353      2.885e-10 

  slope       0.2296      9.746e-10 

  tmpavg      0.2167      7.669e-10 

   pop        0.1953      2.428e-10 

  premax      0.1399      8.428e-10 

   ntl        0.02272      0.0301   

  aspect      0.0186       0.7491   
------------------------------------



``` r
gd(fvc ~ .,data = new.fvc,type = 'interaction')
## Spatial Stratified Heterogeneity Test 
##  
##          Interaction detector
```


-------------------------------------------
 Interactive variable      Interaction     
---------------------- --------------------
    lulc ∩ aspect       Enhance, nonlinear 

     lulc ∩ elev           Enhance, bi-    

      lulc ∩ ntl        Enhance, nonlinear 

      lulc ∩ pop           Enhance, bi-    

    lulc ∩ premax          Enhance, bi-    

    lulc ∩ premin          Enhance, bi-    

    lulc ∩ presum          Enhance, bi-    

     lulc ∩ slope          Enhance, bi-    

    lulc ∩ tmpavg          Enhance, bi-    

    lulc ∩ tmpmax          Enhance, bi-    

    lulc ∩ tmpmin          Enhance, bi-    

    aspect ∩ elev       Enhance, nonlinear 

     aspect ∩ ntl       Enhance, nonlinear 

     aspect ∩ pop       Enhance, nonlinear 

   aspect ∩ premax      Enhance, nonlinear 

   aspect ∩ premin      Enhance, nonlinear 

   aspect ∩ presum         Enhance, bi-    

    aspect ∩ slope      Enhance, nonlinear 

   aspect ∩ tmpavg      Enhance, nonlinear 

   aspect ∩ tmpmax      Enhance, nonlinear 

   aspect ∩ tmpmin      Enhance, nonlinear 

      elev ∩ ntl        Enhance, nonlinear 

      elev ∩ pop           Enhance, bi-    

    elev ∩ premax       Enhance, nonlinear 

    elev ∩ premin          Enhance, bi-    

    elev ∩ presum          Enhance, bi-    

     elev ∩ slope       Enhance, nonlinear 

    elev ∩ tmpavg          Enhance, bi-    

    elev ∩ tmpmax       Enhance, nonlinear 

    elev ∩ tmpmin          Enhance, bi-    

      ntl ∩ pop         Enhance, nonlinear 

     ntl ∩ premax       Enhance, nonlinear 

     ntl ∩ premin       Enhance, nonlinear 

     ntl ∩ presum       Enhance, nonlinear 

     ntl ∩ slope        Enhance, nonlinear 

     ntl ∩ tmpavg       Enhance, nonlinear 

     ntl ∩ tmpmax       Enhance, nonlinear 

     ntl ∩ tmpmin       Enhance, nonlinear 

     pop ∩ premax       Enhance, nonlinear 

     pop ∩ premin          Enhance, bi-    

     pop ∩ presum          Enhance, bi-    

     pop ∩ slope           Enhance, bi-    

     pop ∩ tmpavg       Enhance, nonlinear 

     pop ∩ tmpmax       Enhance, nonlinear 

     pop ∩ tmpmin          Enhance, bi-    

   premax ∩ premin      Enhance, nonlinear 

   premax ∩ presum         Enhance, bi-    

    premax ∩ slope      Enhance, nonlinear 

   premax ∩ tmpavg      Enhance, nonlinear 

   premax ∩ tmpmax      Enhance, nonlinear 

   premax ∩ tmpmin      Enhance, nonlinear 

   premin ∩ presum         Enhance, bi-    

    premin ∩ slope         Enhance, bi-    

   premin ∩ tmpavg         Enhance, bi-    

   premin ∩ tmpmax         Enhance, bi-    

   premin ∩ tmpmin         Enhance, bi-    

    presum ∩ slope         Enhance, bi-    

   presum ∩ tmpavg         Enhance, bi-    

   presum ∩ tmpmax         Enhance, bi-    

   presum ∩ tmpmin         Enhance, bi-    

    slope ∩ tmpavg         Enhance, bi-    

    slope ∩ tmpmax         Enhance, bi-    

    slope ∩ tmpmin         Enhance, bi-    

   tmpavg ∩ tmpmax      Enhance, nonlinear 

   tmpavg ∩ tmpmin      Enhance, nonlinear 

   tmpmax ∩ tmpmin      Enhance, nonlinear 
-------------------------------------------



### You can also use `opgd()` in one time to get result above.


``` r
set.seed(12345678)
fvc_opgd = opgd(fvc ~ ., data = fvc, discnum = 2:15,
                discvar = names(select(fvc,-c(fvc,lulc))),
                cores = 6, type = c('factor','interaction'))
str(fvc_opgd)
## List of 2
##  $ :List of 1
##   ..$ factor: tibble [12 × 3] (S3: tbl_df/tbl/data.frame)
##   .. ..$ variable   : chr [1:12] "presum" "lulc" "premin" "tmpmin" ...
##   .. ..$ Q-statistic: num [1:12] 0.664 0.66 0.467 0.434 0.259 ...
##   .. ..$ P-value    : num [1:12] 6.08e-10 8.78e-10 5.58e-10 4.67e-10 3.13e-10 ...
##   ..- attr(*, "class")= chr "factor_detector"
##  $ :List of 1
##   ..$ interaction: tibble [66 × 6] (S3: tbl_df/tbl/data.frame)
##   .. ..$ variable1                                    : chr [1:66] "lulc" "lulc" "lulc" "lulc" ...
##   .. ..$ variable2                                    : chr [1:66] "aspect" "elev" "ntl" "pop" ...
##   .. ..$ Interaction                                  : chr [1:66] "Enhance, nonlinear" "Enhance, bi-" "Enhance, nonlinear" "Enhance, bi-" ...
##   .. ..$ Variable1 Q-statistics                       : num [1:66] 0.66 0.66 0.66 0.66 0.66 ...
##   .. ..$ Variable2 Q-statistics                       : num [1:66] 0.0186 0.2353 0.0228 0.1953 0.1448 ...
##   .. ..$ Variable1 and Variable2 interact Q-statistics: num [1:66] 0.691 0.821 0.725 0.756 0.769 ...
##   ..- attr(*, "class")= chr "interaction_detector"
```

``` r
fvc_opgd[[1]]
## Spatial Stratified Heterogeneity Test 
##  
##           Factor detector
```


------------------------------------
 variable   Q-statistic    P-value  
---------- ------------- -----------
  presum      0.6642      6.083e-10 

   lulc       0.6597      8.782e-10 

  premin      0.4671      5.581e-10 

  tmpmin      0.4341      4.671e-10 

  tmpmax      0.2594      3.131e-10 

   elev       0.2353      2.885e-10 

  slope       0.2338      7.849e-10 

  tmpavg      0.2249      4.787e-10 

   pop        0.1953      2.428e-10 

  premax      0.1448      1.771e-10 

   ntl        0.02278      0.08141  

  aspect      0.0186       0.7491   
------------------------------------



``` r
fvc_opgd[[2]]
## Spatial Stratified Heterogeneity Test 
##  
##          Interaction detector
```


-------------------------------------------
 Interactive variable      Interaction     
---------------------- --------------------
    lulc ∩ aspect       Enhance, nonlinear 

     lulc ∩ elev           Enhance, bi-    

      lulc ∩ ntl        Enhance, nonlinear 

      lulc ∩ pop           Enhance, bi-    

    lulc ∩ premax          Enhance, bi-    

    lulc ∩ premin          Enhance, bi-    

    lulc ∩ presum          Enhance, bi-    

     lulc ∩ slope          Enhance, bi-    

    lulc ∩ tmpavg          Enhance, bi-    

    lulc ∩ tmpmax          Enhance, bi-    

    lulc ∩ tmpmin          Enhance, bi-    

    aspect ∩ elev       Enhance, nonlinear 

     aspect ∩ ntl       Enhance, nonlinear 

     aspect ∩ pop       Enhance, nonlinear 

   aspect ∩ premax      Enhance, nonlinear 

   aspect ∩ premin      Enhance, nonlinear 

   aspect ∩ presum         Enhance, bi-    

    aspect ∩ slope      Enhance, nonlinear 

   aspect ∩ tmpavg      Enhance, nonlinear 

   aspect ∩ tmpmax      Enhance, nonlinear 

   aspect ∩ tmpmin      Enhance, nonlinear 

      elev ∩ ntl        Enhance, nonlinear 

      elev ∩ pop           Enhance, bi-    

    elev ∩ premax       Enhance, nonlinear 

    elev ∩ premin          Enhance, bi-    

    elev ∩ presum          Weaken, uni-    

     elev ∩ slope          Enhance, bi-    

    elev ∩ tmpavg          Enhance, bi-    

    elev ∩ tmpmax       Enhance, nonlinear 

    elev ∩ tmpmin          Enhance, bi-    

      ntl ∩ pop         Enhance, nonlinear 

     ntl ∩ premax       Enhance, nonlinear 

     ntl ∩ premin       Enhance, nonlinear 

     ntl ∩ presum       Enhance, nonlinear 

     ntl ∩ slope        Enhance, nonlinear 

     ntl ∩ tmpavg       Enhance, nonlinear 

     ntl ∩ tmpmax       Enhance, nonlinear 

     ntl ∩ tmpmin       Enhance, nonlinear 

     pop ∩ premax       Enhance, nonlinear 

     pop ∩ premin          Enhance, bi-    

     pop ∩ presum          Enhance, bi-    

     pop ∩ slope           Enhance, bi-    

     pop ∩ tmpavg       Enhance, nonlinear 

     pop ∩ tmpmax       Enhance, nonlinear 

     pop ∩ tmpmin          Enhance, bi-    

   premax ∩ premin      Enhance, nonlinear 

   premax ∩ presum         Enhance, bi-    

    premax ∩ slope      Enhance, nonlinear 

   premax ∩ tmpavg      Enhance, nonlinear 

   premax ∩ tmpmax      Enhance, nonlinear 

   premax ∩ tmpmin      Enhance, nonlinear 

   premin ∩ presum         Enhance, bi-    

    premin ∩ slope         Enhance, bi-    

   premin ∩ tmpavg         Enhance, bi-    

   premin ∩ tmpmax         Enhance, bi-    

   premin ∩ tmpmin         Enhance, bi-    

    presum ∩ slope         Enhance, bi-    

   presum ∩ tmpavg         Enhance, bi-    

   presum ∩ tmpmax         Enhance, bi-    

   presum ∩ tmpmin         Enhance, bi-    

    slope ∩ tmpavg         Enhance, bi-    

    slope ∩ tmpmax         Enhance, bi-    

    slope ∩ tmpmin         Enhance, bi-    

   tmpavg ∩ tmpmax      Enhance, nonlinear 

   tmpavg ∩ tmpmin         Enhance, bi-    

   tmpmax ∩ tmpmin      Enhance, nonlinear 
-------------------------------------------


