---
title: "Robust Geographical Detector(RGD)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RGD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



### Set up your python dependence

1. install `miniconda`
2. create a new conda env `geocompy` use `conda create -n geocompy python=3.9 -y`
3. activate this env `conda activate geocompy`
4. install `mamba` by `conda install -c conda-forge mamba -y`.
5. set up python packages use `mamba install -c conda-forge numpy==1.23.5 joblib
pandas ruptures -y`

### Load data and package


``` r
library(terra)
library(gdverse)
library(tidyverse)
reticulate::use_condaenv('geocompy')

fvcpath = "https://github.com/SpatLyu/rdevdata/raw/main/FVC.tif"
fvc = terra::rast(paste0("/vsicurl/",fvcpath))
fvc = aggregate(fvc,fact = 5)
fvc
## class       : SpatRaster 
## dimensions  : 84, 114, 13  (nrow, ncol, nlyr)
## resolution  : 5000, 5000  (x, y)
## extent      : -92742.16, 477257.8, 3589385, 4009385  (xmin, xmax, ymin, ymax)
## coord. ref. : Asia_North_Albers_Equal_Area_Conic 
## source(s)   : memory
## names       :       fvc,   premax,    premin,   presum,   tmpmax,    tmpmin, ... 
## min values  : 0.1527159, 111.2089,  2.340401, 3834.887, 10.92638, -9.976424, ... 
## max values  : 0.8905939, 247.1408, 75.933422, 8276.911, 26.72104,  1.101411, ...
```


``` r
names(fvc)
##  [1] "fvc"    "premax" "premin" "presum" "tmpmax" "tmpmin" "tmpavg" "pop"    "ntl"    "lulc"  
## [11] "elev"   "slope"  "aspect"
```

### Convert data from `SpatRaster` to `tibble`


``` r
fvc = as_tibble(terra::as.data.frame(fvc,na.rm = T))
head(fvc)
## # A tibble: 6 × 13
##     fvc premax premin presum tmpmax tmpmin tmpavg   pop   ntl  lulc  elev slope aspect
##   <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
## 1 0.188   163.   6.86  3992.   21.2  -7.09   8.54  5.64  9.10    10 1645.  2.96   122.
## 2 0.162   162.   5.23  3922.   21.7  -6.90   8.92 23.1  10.5     10 1539.  1.86   174.
## 3 0.168   168.   4.15  4040.   21.2  -7.22   8.53  9.73  5.58    10 1611.  3.19   192.
## 4 0.186   174.   5.99  4254.   20.8  -7.42   8.21  6.84  2.89    10 1677.  3.32   213.
## 5 0.189   164.   7.86  4047.   21.2  -7.00   8.58  2.36 12.3     10 1643.  2.79   132.
## 6 0.171   161.   5.23  3944.   21.7  -6.85   8.91  3.17 10.1     10 1553.  1.93   137.
```

### Determine discretization use offline change point detection

Only `lulc` is a discrete category variable in the `fvc` data, we need to discretize others.
We can use `robust_disc()` to discretize them based on offline change point detection.


``` r
tictoc::tic()
new.fvc = robust_disc(fvc ~ .,data = select(fvc,-lulc),discnum = 15,cores = 6)
tictoc::toc()
## 2786 sec elapsed
```


``` r
new.fvc
## # A tibble: 5,240 × 11
##    premax  premin presum tmpmax tmpmin tmpavg pop     ntl     elev    slope   aspect 
##    <chr>   <chr>  <chr>  <chr>  <chr>  <chr>  <chr>   <chr>   <chr>   <chr>   <chr>  
##  1 group10 group1 group1 group8 group4 group5 group7  group14 group13 group10 group4 
##  2 group10 group1 group1 group9 group4 group7 group10 group14 group11 group10 group14
##  3 group11 group1 group1 group8 group4 group5 group8  group14 group13 group10 group14
##  4 group13 group1 group1 group8 group2 group4 group7  group14 group13 group11 group14
##  5 group10 group1 group1 group8 group4 group5 group1  group14 group13 group10 group7 
##  6 group10 group1 group1 group9 group4 group5 group2  group14 group11 group10 group7 
##  7 group10 group1 group1 group9 group4 group7 group8  group14 group9  group6  group4 
##  8 group10 group1 group1 group9 group4 group7 group8  group14 group9  group10 group14
##  9 group10 group1 group1 group8 group4 group5 group10 group14 group13 group10 group14
## 10 group11 group1 group1 group8 group4 group5 group9  group14 group9  group10 group14
## # ℹ 5,230 more rows
```

The `new.fvc` is the discrete result,we can combine it with `fvc` and `lulc` col in `fvc` tibble now.


``` r
new.fvc = bind_cols(select(fvc,fvc,lulc),new.fvc)
new.fvc
## # A tibble: 5,240 × 13
##      fvc  lulc premax  premin presum tmpmax tmpmin tmpavg pop     ntl     elev    slope  aspect
##    <dbl> <dbl> <chr>   <chr>  <chr>  <chr>  <chr>  <chr>  <chr>   <chr>   <chr>   <chr>  <chr> 
##  1 0.188    10 group10 group1 group1 group8 group4 group5 group7  group14 group13 group… group4
##  2 0.162    10 group10 group1 group1 group9 group4 group7 group10 group14 group11 group… group…
##  3 0.168    10 group11 group1 group1 group8 group4 group5 group8  group14 group13 group… group…
##  4 0.186    10 group13 group1 group1 group8 group2 group4 group7  group14 group13 group… group…
##  5 0.189    10 group10 group1 group1 group8 group4 group5 group1  group14 group13 group… group7
##  6 0.171    10 group10 group1 group1 group9 group4 group5 group2  group14 group11 group… group7
##  7 0.153    10 group10 group1 group1 group9 group4 group7 group8  group14 group9  group6 group4
##  8 0.163    10 group10 group1 group1 group9 group4 group7 group8  group14 group9  group… group…
##  9 0.176    10 group10 group1 group1 group8 group4 group5 group10 group14 group13 group… group…
## 10 0.177    10 group11 group1 group1 group8 group4 group5 group9  group14 group9  group… group…
## # ℹ 5,230 more rows
```

### Run geodetector

Then ,we can run geodetector model by `gd()` function.


``` r
gd(fvc ~ .,data = new.fvc,type = 'factor')
## Spatial Stratified Heterogeneity Test 
##  
##           Factor detector         
## 
## | variable | Q-statistic |   P-value    |
## |:--------:|:-----------:|:------------:|
## |  presum  | 0.67445200  | 6.166071e-10 |
## |   lulc   | 0.65972601  | 8.781502e-10 |
## |  premin  | 0.48551635  | 5.461166e-10 |
## |  tmpmin  | 0.45750355  | 6.232301e-10 |
## |  tmpmax  | 0.28155698  | 5.853387e-10 |
## |   elev   | 0.25758875  | 5.407331e-10 |
## |   pop    | 0.25657619  | 4.386063e-10 |
## |  slope   | 0.25254898  | 9.438880e-10 |
## |  tmpavg  | 0.25020311  | 4.200449e-10 |
## |  premax  | 0.16682640  | 9.434108e-10 |
## |  aspect  | 0.03426667  | 6.238625e-02 |
## |   ntl    | 0.02333733  | 4.623048e-10 |
```

``` r
gd(fvc ~ .,data = new.fvc,type = 'interaction')
## Spatial Stratified Heterogeneity Test 
##  
##          Interaction detector         
## 
## | Interactive variable |    Interaction     |
## |:--------------------:|:------------------:|
## |    lulc ∩ premax     |    Enhance, bi-    |
## |    lulc ∩ premin     |    Enhance, bi-    |
## |    lulc ∩ presum     |    Enhance, bi-    |
## |    lulc ∩ tmpmax     |    Enhance, bi-    |
## |    lulc ∩ tmpmin     |    Enhance, bi-    |
## |    lulc ∩ tmpavg     |    Enhance, bi-    |
## |      lulc ∩ pop      |    Enhance, bi-    |
## |      lulc ∩ ntl      |    Enhance, bi-    |
## |     lulc ∩ elev      |    Enhance, bi-    |
## |     lulc ∩ slope     |    Enhance, bi-    |
## |    lulc ∩ aspect     |    Enhance, bi-    |
## |   premax ∩ premin    | Enhance, nonlinear |
## |   premax ∩ presum    |    Enhance, bi-    |
## |   premax ∩ tmpmax    | Enhance, nonlinear |
## |   premax ∩ tmpmin    | Enhance, nonlinear |
## |   premax ∩ tmpavg    | Enhance, nonlinear |
## |     premax ∩ pop     | Enhance, nonlinear |
## |     premax ∩ ntl     | Enhance, nonlinear |
## |    premax ∩ elev     | Enhance, nonlinear |
## |    premax ∩ slope    |    Enhance, bi-    |
## |   premax ∩ aspect    | Enhance, nonlinear |
## |   premin ∩ presum    |    Enhance, bi-    |
## |   premin ∩ tmpmax    |    Enhance, bi-    |
## |   premin ∩ tmpmin    |    Enhance, bi-    |
## |   premin ∩ tmpavg    |    Enhance, bi-    |
## |     premin ∩ pop     |    Enhance, bi-    |
## |     premin ∩ ntl     | Enhance, nonlinear |
## |    premin ∩ elev     |    Enhance, bi-    |
## |    premin ∩ slope    |    Enhance, bi-    |
## |   premin ∩ aspect    |    Enhance, bi-    |
## |   presum ∩ tmpmax    |    Enhance, bi-    |
## |   presum ∩ tmpmin    |    Enhance, bi-    |
## |   presum ∩ tmpavg    |    Enhance, bi-    |
## |     presum ∩ pop     |    Enhance, bi-    |
## |     presum ∩ ntl     | Enhance, nonlinear |
## |    presum ∩ elev     |    Enhance, bi-    |
## |    presum ∩ slope    |    Enhance, bi-    |
## |   presum ∩ aspect    |    Enhance, bi-    |
## |   tmpmax ∩ tmpmin    |    Enhance, bi-    |
## |   tmpmax ∩ tmpavg    | Enhance, nonlinear |
## |     tmpmax ∩ pop     |    Enhance, bi-    |
## |     tmpmax ∩ ntl     | Enhance, nonlinear |
## |    tmpmax ∩ elev     | Enhance, nonlinear |
## |    tmpmax ∩ slope    |    Enhance, bi-    |
## |   tmpmax ∩ aspect    | Enhance, nonlinear |
## |   tmpmin ∩ tmpavg    |    Enhance, bi-    |
## |     tmpmin ∩ pop     |    Enhance, bi-    |
## |     tmpmin ∩ ntl     | Enhance, nonlinear |
## |    tmpmin ∩ elev     |    Enhance, bi-    |
## |    tmpmin ∩ slope    |    Enhance, bi-    |
## |   tmpmin ∩ aspect    |    Enhance, bi-    |
## |     tmpavg ∩ pop     |    Enhance, bi-    |
## |     tmpavg ∩ ntl     | Enhance, nonlinear |
## |    tmpavg ∩ elev     |    Enhance, bi-    |
## |    tmpavg ∩ slope    |    Enhance, bi-    |
## |   tmpavg ∩ aspect    | Enhance, nonlinear |
## |      pop ∩ ntl       | Enhance, nonlinear |
## |      pop ∩ elev      |    Enhance, bi-    |
## |     pop ∩ slope      |    Enhance, bi-    |
## |     pop ∩ aspect     |    Enhance, bi-    |
## |      ntl ∩ elev      | Enhance, nonlinear |
## |     ntl ∩ slope      | Enhance, nonlinear |
## |     ntl ∩ aspect     | Enhance, nonlinear |
## |     elev ∩ slope     |    Enhance, bi-    |
## |    elev ∩ aspect     | Enhance, nonlinear |
## |    slope ∩ aspect    |    Enhance, bi-    |
```

### You can also use `rgd()` in one time to get result above.


``` r
fvc_rgd = rgd(fvc ~ ., data = fvc, discnum = 15,
              discvar = names(select(fvc,-c(fvc,lulc))),
              cores = 6, type = c('factor','interaction'))
str(fvc_rgd)
## List of 2
##  $ :List of 1
##   ..$ factor: tibble [12 × 3] (S3: tbl_df/tbl/data.frame)
##   .. ..$ variable   : chr [1:12] "presum" "lulc" "premin" "tmpmin" ...
##   .. ..$ Q-statistic: num [1:12] 0.674 0.66 0.486 0.458 0.282 ...
##   .. ..$ P-value    : num [1:12] 6.17e-10 8.78e-10 5.46e-10 6.23e-10 5.85e-10 ...
##   ..- attr(*, "class")= chr "factor_detector"
##  $ :List of 1
##   ..$ interaction: tibble [66 × 6] (S3: tbl_df/tbl/data.frame)
##   .. ..$ variable1                                    : chr [1:66] "lulc" "lulc" "lulc" "lulc" ...
##   .. ..$ variable2                                    : chr [1:66] "premax" "premin" "presum" "tmpmax" ...
##   .. ..$ Interaction                                  : chr [1:66] "Enhance, bi-" "Enhance, bi-" "Enhance, bi-" "Enhance, bi-" ...
##   .. ..$ Variable1 Q-statistics                       : num [1:66] 0.66 0.66 0.66 0.66 0.66 ...
##   .. ..$ Variable2 Q-statistics                       : num [1:66] 0.167 0.486 0.674 0.282 0.458 ...
##   .. ..$ Variable1 and Variable2 interact Q-statistics: num [1:66] 0.771 0.791 0.817 0.82 0.848 ...
##   ..- attr(*, "class")= chr "interaction_detector"
```

``` r
fvc_rgd[[1]]
## Spatial Stratified Heterogeneity Test 
##  
##           Factor detector         
## 
## | variable | Q-statistic |   P-value    |
## |:--------:|:-----------:|:------------:|
## |  presum  | 0.67445200  | 6.166071e-10 |
## |   lulc   | 0.65972601  | 8.781502e-10 |
## |  premin  | 0.48551635  | 5.461166e-10 |
## |  tmpmin  | 0.45750355  | 6.232301e-10 |
## |  tmpmax  | 0.28155698  | 5.853387e-10 |
## |   elev   | 0.25758875  | 5.407331e-10 |
## |   pop    | 0.25657619  | 4.386063e-10 |
## |  slope   | 0.25254898  | 9.438880e-10 |
## |  tmpavg  | 0.25020311  | 4.200449e-10 |
## |  premax  | 0.16682640  | 9.434108e-10 |
## |  aspect  | 0.03426667  | 6.238625e-02 |
## |   ntl    | 0.02333733  | 4.623048e-10 |
```

``` r
fvc_rgd[[2]]
## Spatial Stratified Heterogeneity Test 
##  
##          Interaction detector         
## 
## | Interactive variable |    Interaction     |
## |:--------------------:|:------------------:|
## |    lulc ∩ premax     |    Enhance, bi-    |
## |    lulc ∩ premin     |    Enhance, bi-    |
## |    lulc ∩ presum     |    Enhance, bi-    |
## |    lulc ∩ tmpmax     |    Enhance, bi-    |
## |    lulc ∩ tmpmin     |    Enhance, bi-    |
## |    lulc ∩ tmpavg     |    Enhance, bi-    |
## |      lulc ∩ pop      |    Enhance, bi-    |
## |      lulc ∩ ntl      |    Enhance, bi-    |
## |     lulc ∩ elev      |    Enhance, bi-    |
## |     lulc ∩ slope     |    Enhance, bi-    |
## |    lulc ∩ aspect     |    Enhance, bi-    |
## |   premax ∩ premin    | Enhance, nonlinear |
## |   premax ∩ presum    |    Enhance, bi-    |
## |   premax ∩ tmpmax    | Enhance, nonlinear |
## |   premax ∩ tmpmin    | Enhance, nonlinear |
## |   premax ∩ tmpavg    | Enhance, nonlinear |
## |     premax ∩ pop     | Enhance, nonlinear |
## |     premax ∩ ntl     | Enhance, nonlinear |
## |    premax ∩ elev     | Enhance, nonlinear |
## |    premax ∩ slope    |    Enhance, bi-    |
## |   premax ∩ aspect    | Enhance, nonlinear |
## |   premin ∩ presum    |    Enhance, bi-    |
## |   premin ∩ tmpmax    |    Enhance, bi-    |
## |   premin ∩ tmpmin    |    Enhance, bi-    |
## |   premin ∩ tmpavg    |    Enhance, bi-    |
## |     premin ∩ pop     |    Enhance, bi-    |
## |     premin ∩ ntl     | Enhance, nonlinear |
## |    premin ∩ elev     |    Enhance, bi-    |
## |    premin ∩ slope    |    Enhance, bi-    |
## |   premin ∩ aspect    |    Enhance, bi-    |
## |   presum ∩ tmpmax    |    Enhance, bi-    |
## |   presum ∩ tmpmin    |    Enhance, bi-    |
## |   presum ∩ tmpavg    |    Enhance, bi-    |
## |     presum ∩ pop     |    Enhance, bi-    |
## |     presum ∩ ntl     | Enhance, nonlinear |
## |    presum ∩ elev     |    Enhance, bi-    |
## |    presum ∩ slope    |    Enhance, bi-    |
## |   presum ∩ aspect    |    Enhance, bi-    |
## |   tmpmax ∩ tmpmin    |    Enhance, bi-    |
## |   tmpmax ∩ tmpavg    | Enhance, nonlinear |
## |     tmpmax ∩ pop     |    Enhance, bi-    |
## |     tmpmax ∩ ntl     | Enhance, nonlinear |
## |    tmpmax ∩ elev     | Enhance, nonlinear |
## |    tmpmax ∩ slope    |    Enhance, bi-    |
## |   tmpmax ∩ aspect    | Enhance, nonlinear |
## |   tmpmin ∩ tmpavg    |    Enhance, bi-    |
## |     tmpmin ∩ pop     |    Enhance, bi-    |
## |     tmpmin ∩ ntl     | Enhance, nonlinear |
## |    tmpmin ∩ elev     |    Enhance, bi-    |
## |    tmpmin ∩ slope    |    Enhance, bi-    |
## |   tmpmin ∩ aspect    |    Enhance, bi-    |
## |     tmpavg ∩ pop     |    Enhance, bi-    |
## |     tmpavg ∩ ntl     | Enhance, nonlinear |
## |    tmpavg ∩ elev     |    Enhance, bi-    |
## |    tmpavg ∩ slope    |    Enhance, bi-    |
## |   tmpavg ∩ aspect    | Enhance, nonlinear |
## |      pop ∩ ntl       | Enhance, nonlinear |
## |      pop ∩ elev      |    Enhance, bi-    |
## |     pop ∩ slope      |    Enhance, bi-    |
## |     pop ∩ aspect     |    Enhance, bi-    |
## |      ntl ∩ elev      | Enhance, nonlinear |
## |     ntl ∩ slope      | Enhance, nonlinear |
## |     ntl ∩ aspect     | Enhance, nonlinear |
## |     elev ∩ slope     |    Enhance, bi-    |
## |    elev ∩ aspect     | Enhance, nonlinear |
## |    slope ∩ aspect    |    Enhance, bi-    |
```
