# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SRS_PD <- function(yobs, xobs, wt) {
    .Call(`_gdverse_SRS_PD`, yobs, xobs, wt)
}

SRS_MULTIPD <- function(yobs, xobs, wt) {
    .Call(`_gdverse_SRS_MULTIPD`, yobs, xobs, wt)
}

SRS_PDTEST <- function(yobs, xobs, wt) {
    .Call(`_gdverse_SRS_PDTEST`, yobs, xobs, wt)
}

